### ISSUE TITLE
Use summary score instead of span score

### ISSUE THREAD

**Issue by sloria** [behaviorbot/sentiment-bot#19]
The bot checks the first span score returned by the Perspective API here:

https://github.com/behaviorbot/sentiment-bot/blob/e3f6c7be50ebd95ff446fcee475bd23a75388a55/index.js#L34

Why only use the first span score? Wouldn't it be more accurate to use the summary score?

See the [Perspective API docs](https://github.com/conversationai/perspectiveapi/blob/master/api_reference.md#scoring-comments-analyzecomment).

**Comment by hiimbex** [comment]
Good point! I must've misunderstood when first reading the docs. Feel free to either open a PR or I'll make this change shortly.
