### ISSUE TITLE
test(sentiment-bot): Example toxic messages

### ISSUE THREAD

**Issue by Kristinita** [behaviorbot/sentiment-bot#23]
Examples from [**Perspective**](https://www.perspectiveapi.com/):

They are liberal idiots who are uneducated.

Climate change is happening and it's not changing in our favor. If you think differently you're an idiot.

They're allowed to do that. But if they act like assholes about, I will block them.

I think its a farce and stinks like a bathroom after 26 beers

My thoughts are that people should stop being stupid and ignorant. Climate change is scientifically proven. It isn't a debate.

**Comment by Kristinita** [comment]
As can you see, Sentiment Bot doesn't work.

Thanks.

**Comment by hiimbex** [comment]
<img width="926" alt="screen shot 2018-04-09 at 11 28 18 am" src="https://user-images.githubusercontent.com/13410355/38506907-26bb88fe-3be9-11e8-9680-f60c8566ad61.png">

Actually, as you can see, I don't have sentiment-bot enabled for this repository, but I will turn it on now, thanks!

**Comment by Kristinita** [comment]
>but I will turn it on now

OK, if you turn on, toxic messages again:

They are liberal idiots who are uneducated.

Climate change is happening and it's not changing in our favor. If you think differently you're an idiot.

They're allowed to do that. But if they act like assholes about, I will block them.

I think its a farce and stinks like a bathroom after 26 beers

My thoughts are that people should stop being stupid and ignorant. Climate change is scientifically proven. It isn't a debate.

**Comment by hiimbex** [comment]
@Kristinita I am not sure what the problem was with your initial issue, but if the bot fails to comment again, please let me know!
