### ISSUE TITLE
question(docs): toxicity threshold

### ISSUE THREAD

**Issue by Kristinita** [behaviorbot/sentiment-bot#24]
### 1. Summary

It would be nice, if `sentimentBotToxicityThreshold` key description will be more understandable.

### 2. Details

[**Sentiment Bot description**](https://probot.github.io/apps/sentiment-bot/):

```markdown
*Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
Anything higher than this threshold will be marked as toxic and commented on
```

What is “being the most toxic”?

Did I understand correctly that:

+ `0` — maximum words and phrases will be marked as toxic,
+ `.99` — minimum words and phrases will be marked as toxic.

?

Or vice versa?

Thanks.

**Comment by hiimbex** [comment]
The perspective api works by giving any string a toxicity rating. The higher the number, the more toxic the comment was. Therefore if you want the bot to comment only on comments that have a toxicity score from the api of .7 or higher, you'd set that value to .7. If you set this score to .0001 or something very low, the bot might comment on everything, even normal statements!

More details on how the perspective api works here: https://github.com/conversationai/perspectiveapi/blob/master/api_reference.md
