### ISSUE TITLE
Needs documentation

### ISSUE THREAD

**Issue by benbalter** [behaviorbot/sentiment-bot#7]
I went to set up the bot for my own repos, but there was no documentation. :sad:

Would it be possible to add a README like the other behaviorbot plugins? :smile:

**Comment by hiimbex** [comment]
So excited you wanna use the bot! Up until 2 days ago, I did not have access to the right API end points, so this is actually not currently deployed. 

I'm planning on wrapping up the code and adding documentation of course today. Hopefully @bkeepers has some time later this week, and we can get this deployed! I'll update you here when that is the case.

**Comment by benbalter** [comment]
:metal: (was also secretly hoping at least one bot would reply to my issue :smile:)

**Comment by hiimbex** [comment]
@benbalter Sentiment Bot is now live! Install it here: https://github.com/apps/sentiment-bot

Happy Sentimenting!

![](https://media.giphy.com/media/13rfYMzkdi2dws/giphy.gif)
